# Generated by Django 5.0.7 on 2025-01-25 14:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import recruiters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seekers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryForLoc',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictForLoc',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('benefits_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('communication_address', models.CharField(blank=True, max_length=255, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_role', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_type', models.CharField(blank=True, choices=[('Limited liability', 'Limited liability'), ('Sole proprietorship', 'Sole proprietorship'), ('Partnership', 'Partnership'), ('Private limited', 'Private limited'), ('Public limited', 'Public limited'), ('Non-profit', 'Non-Profit'), ('Government', 'Government')], max_length=100, null=True)),
                ('no_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('on_role_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('off_role_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('is_manufacturing_based', models.BooleanField(default=False)),
                ('is_service_based', models.BooleanField(default=False)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_type', models.CharField(blank=True, choices=[('Start-Up', 'Start-Up'), ('Multinational-Corporation', 'MNC'), ('Small and Medium-sized enterprises ', 'SME')], max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=355, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('established_at', models.IntegerField()),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('Back_ifsc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_company_kyc_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), recruiters.models.validate_file_size])),
                ('gst_doc', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_company_kyc_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), recruiters.models.validate_file_size])),
                ('pan_doc', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_company_kyc_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), recruiters.models.validate_file_size])),
                ('list_of_dir_doc', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_company_kyc_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), recruiters.models.validate_file_size])),
                ('bank_account_doc', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_company_kyc_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), recruiters.models.validate_file_size])),
                ('sub_users_limit', models.IntegerField(default=1)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_contact_verified', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_candidate', to='job_seekers.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Fixed-term', 'Fixed-term'), ('Internship', 'Internship')], max_length=100, null=True)),
                ('is_fixed_shift', models.BooleanField(default=False)),
                ('is_rotational_shift', models.BooleanField(default=False)),
                ('is_day_shift', models.BooleanField(default=False)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_onsite', models.BooleanField(default=False)),
                ('is_work_from_home', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, null=True)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date_to_apply', models.DateTimeField(blank=True, null=True)),
                ('opening_count', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('applied_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_post_verified', models.BooleanField(default=False)),
                ('benefit_id', models.ManyToManyField(related_name='benefit_map_jbm', to='recruiters.benefits')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiters.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_by', to='job_seekers.candidates')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_for', to='job_seekers.candidates')),
                ('issued_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_from', to='recruiters.companies')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_in', to='recruiters.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkCandidates',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers_bookmarks', to='job_seekers.candidates')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='recruiters.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_title_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_by', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='recruiters.districtforloc')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='location_id',
            field=models.ManyToManyField(related_name='location_map_jlm', to='recruiters.locations'),
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_qualification_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='qualifications',
            field=models.ManyToManyField(related_name='qualification_map', to='recruiters.qualifications'),
        ),
        migrations.CreateModel(
            name='StateForLoc',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='recruiters.countryforloc')),
            ],
        ),
        migrations.AddField(
            model_name='districtforloc',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='recruiters.stateforloc'),
        ),
        migrations.CreateModel(
            name='SubUserAccess',
            fields=[
                ('subuser_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('can_post_jobs', models.BooleanField(default=False)),
                ('can_edit_jobs', models.BooleanField(default=False)),
                ('can_view_applicants', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers_company', to='recruiters.companies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subuser_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies')),
                ('sub_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
