# Generated by Django 5.0.7 on 2025-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='no_of_employees',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='off_role_employees',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='on_role_employees',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
