# Generated by Django 5.2 on 2025-05-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiters.companies'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='max_experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Fresher'), (1, '1 year'), (2, '2 years'), (3, '3 years'), (5, '5 years'), (7, '7 years'), (10, '10 years'), (15, '15 years'), (20, '20 years'), (25, '25 years'), (30, '30 years'), (30, '35 years'), (30, '40+ years')], null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Fresher'), (1, '1 year'), (2, '2 years'), (3, '3 years'), (5, '5 years'), (7, '7 years'), (10, '10 years'), (15, '15 years'), (20, '20 years'), (25, '25 years'), (30, '30 years'), (30, '35 years'), (30, '40+ years')], null=True),
        ),
    ]
