# Generated by Django 5.2 on 2025-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_alter_jobs_company_alter_jobs_max_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletters',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
