# Generated by Django 5.0.7 on 2025-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_alter_companies_no_of_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='is_manufacturing_based',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='is_service_based',
        ),
        migrations.AddField(
            model_name='companies',
            name='business_model',
            field=models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Service', 'Service')], max_length=100, null=True),
        ),
    ]
