# Generated by Django 5.2 on 2025-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_offerletters_viewed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerletters',
            old_name='is_accepted',
            new_name='is_acknowledged',
        ),
        migrations.RemoveField(
            model_name='offerletters',
            name='accepted_at',
        ),
        migrations.AddField(
            model_name='offerletters',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
