# Generated by Django 5.0.7 on 2025-01-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_remove_companies_is_manufacturing_based_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='business_model',
            new_name='business_type',
        ),
    ]
