# Generated by Django 5.0.7 on 2025-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_rename_business_model_companies_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companies',
            name='established_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('Start-Up', 'Start-Up'), ('Small and Medium-sized enterprises ', 'SME'), ('Multinational-Corporation', 'MNC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
