# Generated by Django 5.2 on 2025-07-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_candidates_resume'),
        ('recruiters', '0004_rename_is_accepted_offerletters_is_acknowledged_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='deadline',
            new_name='hired_date',
        ),
        migrations.AlterUniqueTogether(
            name='positions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hirerequests',
            name='reason_for_leaving',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PositionGroup',
            fields=[
                ('position_group_code', models.AutoField(primary_key=True, serialize=False)),
                ('position_code', models.PositiveIntegerField()),
                ('position_title', models.CharField(max_length=255)),
                ('jd', models.TextField(blank=True, null=True)),
                ('budget', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_position_grp', to='job_seekers.candidates')),
                ('upadted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_position_grp', to='job_seekers.candidates')),
            ],
            options={
                'unique_together': {('company', 'position_code')},
            },
        ),
        migrations.AddField(
            model_name='positions',
            name='position_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='recruiters.positiongroup'),
        ),
        migrations.RemoveField(
            model_name='positions',
            name='company',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='position_code',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='position_title',
        ),
    ]
