# Generated by Django 5.2 on 2025-07-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_candidates_resume'),
        ('recruiters', '0005_rename_deadline_positions_hired_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='hired_date',
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='Supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve3_position_grp', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='hrbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='hrms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='positiongroup',
            name='locations',
        ),
        migrations.AddField(
            model_name='positiongroup',
            name='locations',
            field=models.ManyToManyField(related_name='location_map_plm', to='recruiters.locations'),
        ),
    ]
