# Generated by Django 5.0.7 on 2025-01-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_alter_companies_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='Back_ifsc_no',
            new_name='back_ifsc_no',
        ),
    ]
