# Generated by Django 5.0.7 on 2025-02-08 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_rename_back_ifsc_no_companies_back_ifsc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='admin_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='admin_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='communication_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='official_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='companies',
            name='permanent_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
