# Generated by Django 5.2 on 2025-07-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_remove_positions_hired_date_positiongroup_supervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiongroup',
            old_name='position_group_code',
            new_name='position_group_id',
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirerequests', to='recruiters.positions'),
        ),
    ]
