# Generated by Django 5.2 on 2025-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_rename_position_group_code_positiongroup_position_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiongroup',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
    ]
