# Generated by Django 5.0.7 on 2025-02-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_alter_companies_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='kyc_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
