# Generated by Django 5.0.7 on 2025-02-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0008_companies_kyc_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
