# Generated by Django 5.2 on 2025-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0008_positiongroup_budget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongroup',
            name='position_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
