# Generated by Django 5.2 on 2025-07-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_candidates_resume'),
        ('recruiters', '0009_alter_positiongroup_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequests',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hirerequests',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hirerequests',
            name='position_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_grp_in_hr', to='recruiters.positiongroup'),
        ),
        migrations.AddField(
            model_name='positions',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_in_position', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='positions',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='is_fill',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_in_hr', to='recruiters.positions'),
        ),
    ]
