# Generated by Django 5.0.7 on 2025-03-05 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0009_companies_city_companies_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='refreshed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
