# Generated by Django 5.2 on 2025-04-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_rename_applied_date_onboarding_completed_date_and_more'),
        ('recruiters', '0010_jobs_refreshed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_title', models.CharField(max_length=255)),
                ('position_code', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_position', to='job_seekers.candidates')),
                ('upadted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_position', to='job_seekers.candidates')),
            ],
            options={
                'unique_together': {('company', 'position_code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePositionManager',
            fields=[
                ('employee_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='map_position', to='job_seekers.candidates')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_in_position_manager', to='job_seekers.candidates')),
                ('upadted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_map_position', to='job_seekers.candidates')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.positions')),
            ],
        ),
        migrations.CreateModel(
            name='HireRequests',
            fields=[
                ('hire_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('hire_request_code', models.PositiveIntegerField()),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_hire_request', to='job_seekers.candidates')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_in_hirerequest', to='job_seekers.candidates')),
                ('upadted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_hire_request', to='job_seekers.candidates')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.positions')),
            ],
            options={
                'unique_together': {('company', 'hire_request_code')},
            },
        ),
    ]
