# Generated by Django 5.2 on 2025-07-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0010_hirerequests_is_approve_hirerequests_is_reject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequests',
            name='is_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hirerequests',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
