# Generated by Django 5.2 on 2025-04-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_rename_applied_date_onboarding_completed_date_and_more'),
        ('recruiters', '0011_positions_employeepositionmanager_hirerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='Created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='hire_request_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_title_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='position_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_qualification_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='sub_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers_logs', to='job_seekers.candidates'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepositionmanager',
            unique_together={('position', 'employee_id')},
        ),
        migrations.DeleteModel(
            name='SubUserAccess',
        ),
    ]
