# Generated by Django 5.2 on 2025-07-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0011_hirerequests_is_hire_hirerequests_is_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerequests',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_hr', to='recruiters.positions'),
        ),
    ]
