# Generated by Django 5.2 on 2025-04-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_rename_applied_date_onboarding_completed_date_and_more'),
        ('recruiters', '0012_alter_benefits_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUsers',
            fields=[
                ('subuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_payroll_maker', models.BooleanField(default=False)),
                ('is_payroll_checker', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruiters_company', to='recruiters.companies')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_subusers', to='job_seekers.candidates')),
                ('upadted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_subuser', to='job_seekers.candidates')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruiters_subuser', to='job_seekers.candidates')),
            ],
        ),
    ]
