# Generated by Django 5.2 on 2025-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0012_alter_hirerequests_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequests',
            name='is_offered',
            field=models.BooleanField(default=False),
        ),
    ]
