# Generated by Django 5.2 on 2025-07-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0013_hirerequests_is_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiongroup',
            old_name='upadted_by',
            new_name='updated_by',
        ),
    ]
