# Generated by Django 5.2 on 2025-04-11 08:11

import django.core.validators
import django.db.models.deletion
import recruiters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_jobapplications_hired_by_and_more'),
        ('recruiters', '0013_subusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offers_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to=recruiters.models.upload_offerleters, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), recruiters.models.validate_file_size])),
                ('view_at', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approve_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_offer', to='job_seekers.jobapplications')),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_offer', to='job_seekers.candidates')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_offer', to='recruiters.companies')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generate_offer', to='job_seekers.candidates')),
            ],
        ),
    ]
