# Generated by Django 5.2 on 2025-04-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_jobapplications_hired_by_and_more'),
        ('recruiters', '0014_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='OfferLetters',
        ),
    ]
