# Generated by Django 5.2 on 2025-07-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0014_rename_upadted_by_positiongroup_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequests',
            name='is_join',
            field=models.BooleanField(default=False),
        ),
    ]
