# Generated by Django 5.2 on 2025-04-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0015_rename_offers_offerletters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerletters',
            old_name='view_at',
            new_name='is_view',
        ),
    ]
