# Generated by Django 5.2 on 2025-07-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0015_hirerequests_is_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerequests',
            old_name='upadted_by',
            new_name='updated_by',
        ),
    ]
