# Generated by Django 5.2 on 2025-04-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0016_rename_view_at_offerletters_is_view'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeepositionmanager',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeepositionmanager',
            name='hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiters.hirerequests'),
        ),
        migrations.AddField(
            model_name='hirerequests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
