# Generated by Django 5.2 on 2025-07-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0016_rename_upadted_by_hirerequests_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='position_grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_post_position_grp', to='recruiters.positiongroup'),
        ),
    ]
