# Generated by Django 5.2 on 2025-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0017_jobs_position_grp'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiongroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
