# Generated by Django 5.2 on 2025-04-24 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_jobapplications_hired_by_and_more'),
        ('recruiters', '0017_alter_employeepositionmanager_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_job_post', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
