# Generated by Django 5.2 on 2025-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0018_positiongroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
    ]
