# Generated by Django 5.2 on 2025-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0018_jobs_created_at_jobs_created_by_alter_jobs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
