# Generated by Django 5.2 on 2025-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0019_jobs_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('CTC', 'CTC'), ('Take home', 'Take home'), ('Per year', 'Per year'), ('Per month', 'Per month'), ('Per hour', 'Per hour')], default='CTC', max_length=10, null=True),
        ),
    ]
