# Generated by Django 5.2 on 2025-07-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0021_alter_candidates_candidate_uuid'),
        ('recruiters', '0019_alter_jobs_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepositionmanager',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_position', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='employeepositionmanager',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_in_position_manager', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='employeepositionmanager',
            name='upadted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_map_position', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_hire_request', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_in_hirerequest', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='hirerequests',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_hire_request', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_job_post', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_hire_request', to='recruiters.hirerequests'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='position_grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post_position_grp', to='recruiters.positiongroup'),
        ),
        migrations.AlterField(
            model_name='offerletters',
            name='approve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_offer', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='offerletters',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generate_offer', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve3_position_grp', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_position_grp', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positiongroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_position_grp', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_position', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_in_position', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='upadted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_position', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='subusers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters_company', to='recruiters.companies'),
        ),
        migrations.AlterField(
            model_name='subusers',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_subusers', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='subusers',
            name='upadted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_subuser', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='subusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters_subuser', to='job_seekers.candidates'),
        ),
    ]
