# Generated by Django 5.2 on 2025-04-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_jobapplications_hired_by_and_more'),
        ('recruiters', '0020_jobs_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_post_hire_request', to='recruiters.hirerequests'),
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_post_skills', to='job_seekers.skills'),
        ),
    ]
