# Generated by Django 5.2 on 2025-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0020_alter_employeepositionmanager_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='benefit_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='benefit_map_jbm', to='recruiters.benefits'),
        ),
    ]
