from django.contrib import admin
from .models import *

admin.site.register(Candidates)
admin.site.register(Bookmarks)
admin.site.register(Onboarding)
admin.site.register(Familys)
admin.site.register(JobApplications)
admin.site.register(AdditionalInfo)
admin.site.register(DomainForSkill)
admin.site.register(Skills)
admin.site.register(LevelForEdu)
admin.site.register(CourseForEdu)
admin.site.register(SpecificationForEdu)
admin.site.register(EducationType)
admin.site.register(EmployemntType)
admin.site.register(Languages)
admin.site.register(UserLanguages)
admin.site.register(UserLocations)
admin.site.register(EducationMap)
admin.site.register(Employment)
admin.site.register(Internship)
admin.site.register(OnboardingDocumentRequirement)
