# Generated by Django 5.2 on 2025-08-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('job_seekers', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_created_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='packages',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_package', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='packages',
            name='upadted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update_package', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='packageusage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiters.companies'),
        ),
        migrations.AddField(
            model_name='packageusage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.packages'),
        ),
        migrations.AddField(
            model_name='packageusage',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_package', to='job_seekers.candidates'),
        ),
    ]
