# Generated by Django 5.2 on 2025-04-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
        ('job_seekers', '0004_rename_applied_date_onboarding_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_created_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='job_seekers.candidates'),
        ),
    ]
