# Generated by Django 5.2 on 2025-04-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_packages_packageusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageusage',
            name='saved',
        ),
    ]
