# Generated by Django 5.2 on 2025-08-10 05:05

import django.core.validators
import job_seekers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarked_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('work_status', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_pic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), job_seekers.models.validate_file_size])),
                ('resume', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), job_seekers.models.validate_file_size])),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('present_ctc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('present_ctc_type', models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True)),
                ('present_take_home_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('present_take_home_type', models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True)),
                ('expected_ctc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_ctc_type', models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True)),
                ('expected_take_home_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_take_home_type', models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True)),
                ('monthly_incentive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_yearly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skill', models.TextField(blank=True, max_length=300, null=True)),
                ('present_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('work_experience_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, choices=[('immediate', 'Immediate Joiner'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('90_days', '90 Days'), ('more_90', 'More than 90 Days')], max_length=20, null=True)),
                ('notice_period_negotiable', models.BooleanField(default=False)),
                ('is_rotate_shift', models.BooleanField(default=False)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_relocate', models.BooleanField(default=False)),
                ('professional_summary', models.TextField(blank=True, max_length=500, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('email_otp_count', models.IntegerField(default=3)),
                ('phone_otp_count', models.IntegerField(default=3)),
                ('bookmarks_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseForEdu',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainForSkill',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationMap',
            fields=[
                ('edu_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_joining', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True)),
                ('year_of_passing', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True)),
                ('currently', models.BooleanField(default=False)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'Pdf']), job_seekers.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('edu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployemntType',
            fields=[
                ('emp_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('work_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_role', models.CharField(max_length=200)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dol', models.DateField(blank=True, null=True)),
                ('currently', models.BooleanField(default=False)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Familys',
            fields=[
                ('family_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('NotDisclosed', 'NotDisclosed')], max_length=50)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister')], max_length=50)),
                ('aadhar_no', models.BigIntegerField(blank=True, null=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internship_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_role', models.CharField(max_length=200)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dol', models.DateField(blank=True, null=True)),
                ('what_did', models.TextField(blank=True, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('appplicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Viewed', 'Viewed'), ('Shortlisted', 'Shortlisted'), ('Interviewed', 'Interviewed'), ('Selected', 'Selected'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('not_shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LevelForEdu',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('Onbording_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_two', models.BigIntegerField(blank=True, null=True)),
                ('communication_country', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_state', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_city', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_address', models.CharField(blank=True, max_length=255, null=True)),
                ('communication_pincode', models.IntegerField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dol', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('bank_book', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('pf', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_uan', models.CharField(blank=True, max_length=20, null=True)),
                ('esic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('pan_card', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('address_proof', models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size])),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingDocumentRequirement',
            fields=[
                ('company_doc_is_required_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationForEdu',
            fields=[
                ('specification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguages',
            fields=[
                ('user_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_speak', models.BooleanField(default=False)),
                ('proficiency', models.CharField(blank=True, choices=[('Proficient', 'Proficient'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=50, null=True)),
            ],
        ),
    ]
