# Generated by Django 5.2 on 2025-08-10 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seekers', '0001_initial'),
        ('recruiters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='recruiters.jobs'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_info', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postinfo', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='educationmap',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_to_edu_map', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='educationmap',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_type_map', to='job_seekers.educationtype'),
        ),
        migrations.AddField(
            model_name='employment',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_company', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='employment',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_type', to='job_seekers.employemnttype'),
        ),
        migrations.AddField(
            model_name='familys',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_family', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='internship',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship_company', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_form', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='hired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hired_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='interview_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='recruiters.jobs'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications_offer', to='recruiters.offerletters'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewselected_byed_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='shortlisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='familys',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_family_job', to='job_seekers.jobapplications'),
        ),
        migrations.AddField(
            model_name='languages',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='courseforedu',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='job_seekers.levelforedu'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_candidate', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_company', to='recruiters.companies'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_created_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_job', to='job_seekers.jobapplications'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_opened_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_verified_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='onboardingdocumentrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies'),
        ),
        migrations.AddField(
            model_name='skills',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Skill_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='skills',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='job_seekers.domainforskill'),
        ),
        migrations.AddField(
            model_name='specificationforedu',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='job_seekers.courseforedu'),
        ),
        migrations.AddField(
            model_name='specificationforedu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='educationmap',
            name='edu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_to_user_map', to='job_seekers.specificationforedu'),
        ),
        migrations.AddField(
            model_name='userlanguages',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_language', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='userlanguages',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_user', to='job_seekers.languages'),
        ),
    ]
