# Generated by Django 5.0.7 on 2025-01-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familys',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_family_job', to='job_seekers.jobapplications'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='applied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_job', to='job_seekers.jobapplications'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_candidate', to='job_seekers.candidates'),
        ),
    ]
