# Generated by Django 5.2 on 2025-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseforedu',
            name='code',
        ),
        migrations.AlterField(
            model_name='courseforedu',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
