# Generated by Django 5.2 on 2025-08-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='appplicant_id',
            new_name='applicant_id',
        ),
    ]
