# Generated by Django 5.2 on 2025-05-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_remove_courseforedu_code_alter_courseforedu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='not_shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Skill_by', to='job_seekers.candidates'),
        ),
        migrations.AlterField(
            model_name='specificationforedu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_by', to='job_seekers.candidates'),
        ),
    ]
