# Generated by Django 5.0.7 on 2025-01-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_familys_job_post_onboarding_applied_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='applied_date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_opened_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onbording_verified_by', to='job_seekers.candidates'),
        ),
    ]
