# Generated by Django 5.2 on 2025-05-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_jobapplications_not_shortlisted_at_and_more'),
        ('recruiters', '0003_offerletters_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications_offer', to='recruiters.offerletters'),
        ),
    ]
