# Generated by Django 5.2 on 2025-04-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_rename_applied_date_onboarding_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='hired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hired_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='interview_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewselected_byed_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='shortlisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='job_seekers.candidates'),
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='job_seekers.candidates'),
        ),
    ]
