# Generated by Django 5.2 on 2025-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_jobapplications_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
    ]
