# Generated by Django 5.2 on 2025-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0006_alter_candidates_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmap',
            name='year_of_joining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
