# Generated by Django 5.2 on 2025-06-15 05:18

import django.core.validators
import django.db.models.deletion
import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0008_employemnttype_alter_educationmap_year_of_joining_and_more'),
        ('recruiters', '0004_rename_is_accepted_offerletters_is_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='esic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_onboarding, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), job_seekers.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pf_uan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingDocumentRequirement',
            fields=[
                ('company_doc_is_required_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.companies')),
            ],
        ),
    ]
