# Generated by Django 5.2 on 2025-06-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0009_onboarding_aadhar_number_onboarding_account_number_and_more'),
        ('recruiters', '0004_rename_is_accepted_offerletters_is_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_company', to='recruiters.companies'),
        ),
    ]
