# Generated by Django 5.2 on 2025-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0010_onboarding_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='languages',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='professional_summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='skill',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
