# Generated by Django 5.2 on 2025-06-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0011_remove_candidates_languages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocations',
        ),
    ]
