# Generated by Django 5.2 on 2025-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0012_delete_userlocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
