# Generated by Django 5.2 on 2025-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0013_alter_candidates_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmap',
            name='currently',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='currently',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
