# Generated by Django 5.2 on 2025-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0014_educationmap_currently_employment_currently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='educationmap',
            name='currently',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employment',
            name='currently',
            field=models.BooleanField(default=False),
        ),
    ]
