# Generated by Django 5.2 on 2025-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0015_remove_candidates_work_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='expected_ctc',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='expected_take_home',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='present_ctc',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='present_take_home',
        ),
        migrations.AddField(
            model_name='candidates',
            name='work_experience_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='work_experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
