# Generated by Django 5.2 on 2025-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0016_remove_candidates_expected_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='expected_ctc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='expected_ctc_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='expected_take_home_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='expected_take_home_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='notice_period',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate Joiner'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('90_days', '90 Days'), ('more_90', 'More than 90 Days')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='notice_period_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidates',
            name='present_ctc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='present_ctc_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='present_take_home_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='present_take_home_type',
            field=models.CharField(blank=True, choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('per_week', 'Per Week'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('one_time', 'One-Time Payment'), ('not_disclosed', 'Not Disclosed')], max_length=20, null=True),
        ),
    ]
