# Generated by Django 5.2 on 2025-07-03 12:01

import django.core.validators
import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0017_candidates_expected_ctc_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), job_seekers.models.validate_file_size]),
        ),
    ]
