# Generated by Django 5.2 on 2025-07-25 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_alter_candidates_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='candidate_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
