# Generated by Django 5.2 on 2025-07-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0021_alter_candidates_candidate_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
