# Generated by Django 5.2 on 2025-07-29 15:30

import django.core.validators
import django.utils.timezone
import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0022_candidates_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=job_seekers.models.upload_profile_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), job_seekers.models.validate_file_size]),
        ),
    ]
